### PR TITLE
Make typography refinements

### PR DESCRIPTION
**Pull request by plhnk**
Updates to styles, as well as component css and html files for more consistency.

### CODE REVIEW

**Comment by westonhancock** [comment]
@plhnk,

Have these changes been tested?

**Comment by phillipchan2** [comment]
YEAH PAUL

**Comment by plhnk** [comment]
@westonhancock @phillipchan2 — I have not tested these changes, from my perspective, this pull-request is the fulfilling of [LRDESIGN-7863](https://issues.liferay.com/browse/LRDESIGN-7863), and the testing and code review should be part of [LRIS-25875](https://issues.liferay.com/browse/LRIS-25875). 

This is slightly different than our typical "design" process, but I wanted to make it more efficient.

**Comment by westonhancock** [comment]
Thanks @plhnk

**Pull request closed without merging**
